### ISSUE TITLE
Safe to include token?

### ISSUE THREAD

**Issue by selbekk** [screentek/Sanity#1]
Sanity Studio is a client side application, so anything we put into it must be non-sensitive. If I enter my imageshop token into the config, it'll show up in the client bundle, which in turn will make it available to any attacker that looks through that bundle.

In other words, if we include the imagebank token, it's available to "everyone". 

Is there a way to avoid this? And if not, do you offer a read-only token, that only lets us read from our database? We would hate waking up one morning with a bunch of nasty photos in our library being uploaded from an attacker.

**Comment by hognescreentek** [comment]
Administrators in Imageshop can themselves issue tokens and change access rights for token. It is possible to prohibit uploading for the token, which will make them in effect read only and no files can then be uploaded or replaced with the token. If you in addition restrict the token only to interfaces which are public or a special interface intended only to be used with web images, the risk is minimal. It is recommended to restrict the access of the token as much as possible. Read more here about [how to issue tokens in Imageshop](https://helpdesk.imageshop.org/en/support/solutions/articles/80001089250-api-access). 

We will check out the possibility to hide the token from the configuration.

**Comment by peec** [comment]
Thank you for reporting :) fixed in 1.3.0
