### ISSUE TITLE
Consistent casing

### ISSUE THREAD

**Issue by selbekk** [screentek/Sanity#3]
The options available to the Sanity plugin are all uppercase, with some underscores thrown in every once in a while.

In JavaScript, we typically use camelCase for option names. In addition, it's a bit confusing as a new user to split the different words (especially when some words are split correctly into several words, and some are not). 

Is this something you could consider changing? It would be a breaking change, but a breaking change a lot of people would prefer. Also, since the plugin is pretty new, not a lot of people would notice.

**Comment by peec** [comment]
Hello,

Thank you for reporting,

I agree and we did this change in the new 1.4.0 release.

**Comment by selbekk** [comment]
Thanks!

One request though: if you're going to use semver, make sure to bump to a new major version everytime you add a breaking change.
