### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by largis21** [screentek/Sanity#4]
When setting up the plugin on a NextJs project - I get the error `Window is not defined`. This is a common issue on SSR applications. I can get it working in the Next app router but the studio runs too slow for it to be viable. In the pages router I cant get it working at all, even after doing some client side only hacks.

![image](https://github.com/screentek/Sanity/assets/65016384/a387cb3a-f0af-49e0-9bd9-bafcabdfe103)

**Comment by peec** [comment]
Hi,

Thank you for reporting,

This is now fixed in latest version, 1.4.1.
